### ISSUE TITLE
Setup on Debian broken due to missing $lts param

### ISSUE THREAD

**Issue by maxenced** [rtyler/puppet-jenkins#42]
$lts is not put as param for jenkins::repo::debian, so setup on debian fails with : 

```
Invalid parameter lts at /etc/puppet/modules/jenkins/manifests/repo.pp:21 
```

**Comment by cyberwolf** [comment]
This is a critical problem here as well. The fix seems to be correct to me.

**Comment by matthewbarr** [comment]
Hmm.. We will likely need to test / fix the slave code. I know I wrote it for RHEL, and it was POC, not fully fleshed for Debian.

**Comment by Boran** [comment]
The fix is just to add "( $lts=0 )" in manifests/repo/debian.pp. To be more specifc.
`git diff
diff --git a/manifests/repo/debian.pp b/manifests/repo/debian.pp
index b10ffcf..a337264 100644
--- a/manifests/repo/debian.pp
+++ b/manifests/repo/debian.pp
@@ -1,4 +1,4 @@
-class jenkins::repo::debian {
+class jenkins::repo::debian ( $lts=0 ) {
     if $lts == 0 {
            apt::source { 'jenkins':
              location    => 'http://pkg.jenkins-ci.org/debian',`
I dont use slave mode yet, but at least needed the fix to get going with this module :-)

**Comment by rtyler** [comment]
This has been resolved and will be pushed to the forge "real soon now" (after I test this stuff)
